Vagrant.configure("2") do |config|
  config.vm.define "gluster1" do |gluster1|
    gluster1.vm.box = "generic/debian12"
#	gluster1.vm.box_version = "202112.20.0"
	gluster1.vm.hostname = "gluster1"
    gluster1.vm.provider "vmware_desktop" do |v|
    v.vmx['displayname'] = 'gluster1'
    v.gui = true
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
	end
	$script1= <<-SCRIPT
echo Configuration de la VM en cours...
date > /etc/vagrant_provisioned_at
echo ----Mise à jour des dépôts----
sleep 3s
sudo apt update
sleep 3s
echo ----Installation Prerequis TP----
sleep 3s
sudo apt install -y curl wget gnupg lsb-release software-properties-common net-tools glusterfs-server docker.io docker-compose
sleep 3s
echo ----Configuration IP----
sleep 3s
ip a
SCRIPT


  gluster1.vm.provision "shell", inline: $script1
  end
  
  config.vm.define "gluster2" do |gluster2|
    gluster2.vm.box = "generic/debian12"
#	gluster2.vm.box_version = "202112.20.0"
	gluster2.vm.hostname = "gluster2"
	gluster2.vm.provider "vmware_desktop" do |v|
    v.vmx['displayname'] = 'gluster2'
    v.gui = true
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
	end
	$script2= <<-SCRIPT
echo Configuration de la VM en cours...
date > /etc/vagrant_provisioned_at
echo ----Mise à jour des dépôts----
sleep 3s
sudo apt update
sleep 3s
echo ----Installation Prerequis TP----
sleep 3s
sudo apt install -y curl wget gnupg lsb-release software-properties-common net-tools glusterfs-server docker.io docker-compose
sleep 3s
echo ----Configuration IP----
sleep 3s
ip a
SCRIPT


  gluster2.vm.provision "shell", inline: $script2
  end
  
  config.vm.define "gluster3" do |gluster3|
    gluster3.vm.box = "generic/debian12"
#	gluster3.vm.box_version = "202112.20.0"
	gluster3.vm.hostname = "gluster3"
	gluster3.vm.provider "vmware_desktop" do |v|
    v.vmx['displayname'] = 'gluster3'
    v.gui = true
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
	end
		$script3= <<-SCRIPT
echo Configuration de la VM en cours...
date > /etc/vagrant_provisioned_at
echo ----Mise à jour des dépôts----
sleep 3s
sudo apt update
sleep 3s
echo ----Installation Prerequis TP----
sleep 3s
sudo apt install -y curl wget gnupg lsb-release software-properties-common net-tools glusterfs-server docker.io docker-compose
sleep 3s
echo ----Configuration IP----
sleep 3s
ip a
SCRIPT


  gluster3.vm.provision "shell", inline: $script3
  end
  
  config.vm.define "swarmmanager" do |swarmmanager|
    swarmmanager.vm.box = "generic/debian12"
#	swarmmanager.vm.box_version = "202112.20.0"
	swarmmanager.vm.hostname = "swarm-manager"
	swarmmanager.vm.provider "vmware_desktop" do |v|
    v.vmx['displayname'] = 'swarm-manager'
    v.gui = true
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
	end
		$script4= <<-SCRIPT
echo Configuration de la VM en cours...
date > /etc/vagrant_provisioned_at
echo ----Mise à jour des dépôts----
sleep 3s
sudo apt update
sleep 3s
echo ----Installation Prerequis TP----
sleep 3s
sudo apt install -y curl wget gnupg lsb-release software-properties-common net-tools docker.io docker-compose
sleep 3s
echo ----Configuration IP----
sleep 3s
ip a
SCRIPT


  swarmmanager.vm.provision "shell", inline: $script4
  end

end